name: Send Hello Email

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email Notification
        uses: vaighai/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL }}
          to: vaighaiselvan.k@crestron.com
          from: ${{ secrets.EMAIL }}
          subject: Hello from GitHub Actions
          body: Hello! This is a test email sent by a GitHub Actions workflow.
